/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BreadcrumbView: typeof import('./components/common/Breadcrumb/BreadcrumbView.vue')['default']
    ButtonView: typeof import('./components/common/Button/ButtonView.vue')['default']
    DialogView: typeof import('./components/common/Dialog/DialogView.vue')['default']
    FieldMatchingDisplay: typeof import('./components/FieldMatchingDisplay.vue')['default']
    FlatButton: typeof import('./components/common/Button/FlatButton.vue')['default']
    IconButton: typeof import('./components/common/Button/IconButton.vue')['default']
    IconButtonImageView: typeof import('./components/common/Button/IconButtonImageView.vue')['default']
    IconView: typeof import('./components/common/Icon/IconView.vue')['default']
    OutlinedView: typeof import('./components/common/Button/OutlinedView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SnackbarToast: typeof import('./components/SnackbarToast.vue')['default']
    WorkorderCreation: typeof import('./components/WorkorderCreation.vue')['default']
    WorkorderTable: typeof import('./components/WorkorderTable.vue')['default']
  }
}
